//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motor_Vehicle_Registration.Fitness_Check_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Fitness_Check_Service.Fitness_Check_WSSoap")]
    public interface Fitness_Check_WSSoap {
        
        // CODEGEN: Generating message contract since element name regNum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_Fitness", ReplyAction="*")]
        Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponse Check_Fitness(Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_Fitness", ReplyAction="*")]
        System.Threading.Tasks.Task<Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponse> Check_FitnessAsync(Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Check_FitnessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check_Fitness", Namespace="http://tempuri.org/", Order=0)]
        public Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequestBody Body;
        
        public Check_FitnessRequest() {
        }
        
        public Check_FitnessRequest(Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Check_FitnessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regNum;
        
        public Check_FitnessRequestBody() {
        }
        
        public Check_FitnessRequestBody(string regNum) {
            this.regNum = regNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Check_FitnessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check_FitnessResponse", Namespace="http://tempuri.org/", Order=0)]
        public Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponseBody Body;
        
        public Check_FitnessResponse() {
        }
        
        public Check_FitnessResponse(Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Check_FitnessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Check_FitnessResult;
        
        public Check_FitnessResponseBody() {
        }
        
        public Check_FitnessResponseBody(string Check_FitnessResult) {
            this.Check_FitnessResult = Check_FitnessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Fitness_Check_WSSoapChannel : Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Fitness_Check_WSSoapClient : System.ServiceModel.ClientBase<Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap>, Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap {
        
        public Fitness_Check_WSSoapClient() {
        }
        
        public Fitness_Check_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Fitness_Check_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Fitness_Check_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Fitness_Check_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponse Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap.Check_Fitness(Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest request) {
            return base.Channel.Check_Fitness(request);
        }
        
        public string Check_Fitness(string regNum) {
            Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest inValue = new Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest();
            inValue.Body = new Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequestBody();
            inValue.Body.regNum = regNum;
            Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponse retVal = ((Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap)(this)).Check_Fitness(inValue);
            return retVal.Body.Check_FitnessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponse> Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap.Check_FitnessAsync(Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest request) {
            return base.Channel.Check_FitnessAsync(request);
        }
        
        public System.Threading.Tasks.Task<Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessResponse> Check_FitnessAsync(string regNum) {
            Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest inValue = new Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequest();
            inValue.Body = new Motor_Vehicle_Registration.Fitness_Check_Service.Check_FitnessRequestBody();
            inValue.Body.regNum = regNum;
            return ((Motor_Vehicle_Registration.Fitness_Check_Service.Fitness_Check_WSSoap)(this)).Check_FitnessAsync(inValue);
        }
    }
}
